### ISSUE TITLE
Add handling of shapefile polylines (patch included)

### ISSUE THREAD

**Issue by tml1024** [roznet/rzexternal#1]
Hi there,

I wanted to get a quick view of the shoreline shapefiles available on https://www.naturalearthdata.com/downloads/10m-physical-vectors/ and tried your Shapefile Viewer. However nothing showed up. So I got the source code and investigated, and noticed that polylines (SHPT_ARC) were not handled. This patch adds that, and seems to work.

--tml

[0001-Add-handling-of-shapefile-polylines.patch.txt](https://github.com/roznet/rzexternal/files/6613785/0001-Add-handling-of-shapefile-polylines.patch.txt)

**Comment by roznet** [comment]
This looks great, thanks for doing this.
Do you want to send a pull request? Alternatively, I can just apply your patch. 
let me know

**Comment by tml1024** [comment]
You can just apply the patch as such, for a change this small I was too lazy to do a proper PR...

**Comment by roznet** [comment]
cool, will do. thanks a lot!
